//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 05:06:49 PM CET 
//


package com.bpcs.suny.tool.xml.request.bookingRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}UserType"/>
 *         &lt;element ref="{}LanguageId"/>
 *         &lt;element ref="{}OperatorId"/>
 *         &lt;element name="Broker" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{}BrokerId"/>
 *         &lt;element ref="{}BrokerNo" minOccurs="0"/>
 *         &lt;element ref="{}BrokerSubExtRef" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}AgencyId"/>
 *           &lt;element ref="{}MarkUpRel" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}OutputConfiguration" minOccurs="0"/>
 *         &lt;element ref="{}Provider" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userType",
    "languageId",
    "operatorId",
    "broker",
    "brokerId",
    "brokerNo",
    "brokerSubExtRef",
    "agencyId",
    "markUpRel",
    "outputConfiguration",
    "provider"
})
@XmlRootElement(name = "Administration")
public class Administration {

    @XmlElement(name = "UserType", required = true)
    protected String userType;
    @XmlElement(name = "LanguageId", required = true)
    protected String languageId;
    @XmlElement(name = "OperatorId")
    protected long operatorId;
    @XmlElement(name = "Broker")
    protected int broker;
    @XmlElement(name = "BrokerId")
    protected long brokerId;
    @XmlElement(name = "BrokerNo")
    protected String brokerNo;
    @XmlElement(name = "BrokerSubExtRef")
    protected String brokerSubExtRef;
    @XmlElement(name = "AgencyId")
    protected Long agencyId;
    @XmlElement(name = "MarkUpRel")
    protected String markUpRel;
    @XmlElement(name = "OutputConfiguration")
    protected OutputConfiguration outputConfiguration;
    @XmlElement(name = "Provider")
    protected String provider;

    /**
     * Gets the value of the userType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserType() {
        return userType;
    }

    /**
     * Sets the value of the userType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserType(String value) {
        this.userType = value;
    }

    /**
     * Gets the value of the languageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageId() {
        return languageId;
    }

    /**
     * Sets the value of the languageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageId(String value) {
        this.languageId = value;
    }

    /**
     * Gets the value of the operatorId property.
     * 
     */
    public long getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     */
    public void setOperatorId(long value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the broker property.
     * 
     */
    public int getBroker() {
        return broker;
    }

    /**
     * Sets the value of the broker property.
     * 
     */
    public void setBroker(int value) {
        this.broker = value;
    }

    /**
     * Gets the value of the brokerId property.
     * 
     */
    public long getBrokerId() {
        return brokerId;
    }

    /**
     * Sets the value of the brokerId property.
     * 
     */
    public void setBrokerId(long value) {
        this.brokerId = value;
    }

    /**
     * Gets the value of the brokerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerNo() {
        return brokerNo;
    }

    /**
     * Sets the value of the brokerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerNo(String value) {
        this.brokerNo = value;
    }

    /**
     * Gets the value of the brokerSubExtRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerSubExtRef() {
        return brokerSubExtRef;
    }

    /**
     * Sets the value of the brokerSubExtRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerSubExtRef(String value) {
        this.brokerSubExtRef = value;
    }

    /**
     * Gets the value of the agencyId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAgencyId() {
        return agencyId;
    }

    /**
     * Sets the value of the agencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAgencyId(Long value) {
        this.agencyId = value;
    }

    /**
     * Gets the value of the markUpRel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkUpRel() {
        return markUpRel;
    }

    /**
     * Sets the value of the markUpRel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkUpRel(String value) {
        this.markUpRel = value;
    }

    /**
     * Gets the value of the outputConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link OutputConfiguration }
     *     
     */
    public OutputConfiguration getOutputConfiguration() {
        return outputConfiguration;
    }

    /**
     * Sets the value of the outputConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputConfiguration }
     *     
     */
    public void setOutputConfiguration(OutputConfiguration value) {
        this.outputConfiguration = value;
    }

    /**
     * Provider wird an TDVA weitergereicht CRS-Funktion
     * 						
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

}
