//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 05:06:49 PM CET 
//


package com.bpcs.suny.tool.xml.request.bookingRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}LogIn" minOccurs="0"/>
 *         &lt;element ref="{}PartnerNo"/>
 *         &lt;element ref="{}CustomerNo"/>
 *         &lt;element ref="{}CustomerType"/>
 *         &lt;element ref="{}Password" minOccurs="0"/>
 *         &lt;element ref="{}SalutationId" minOccurs="0"/>
 *         &lt;element ref="{}Name" minOccurs="0"/>
 *         &lt;element ref="{}FirstName" minOccurs="0"/>
 *         &lt;element ref="{}Street" minOccurs="0"/>
 *         &lt;element ref="{}ZipCode" minOccurs="0"/>
 *         &lt;element ref="{}City" minOccurs="0"/>
 *         &lt;element ref="{}CountryId" minOccurs="0"/>
 *         &lt;element ref="{}PhoneCountry" minOccurs="0"/>
 *         &lt;element ref="{}PhoneArea" minOccurs="0"/>
 *         &lt;element ref="{}PhoneExt" minOccurs="0"/>
 *         &lt;element ref="{}FaxCountry" minOccurs="0"/>
 *         &lt;element ref="{}FaxArea" minOccurs="0"/>
 *         &lt;element ref="{}FaxExt" minOccurs="0"/>
 *         &lt;element ref="{}EMail" minOccurs="0"/>
 *         &lt;element ref="{}CreditCard" minOccurs="0"/>
 *         &lt;element ref="{}BonusCard" minOccurs="0"/>
 *         &lt;element ref="{}DateOfBirth" minOccurs="0"/>
 *         &lt;element ref="{}DocChannel" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Customer")
public class Customer {

    @XmlElement(name = "LogIn")
    protected String logIn;
    @XmlElement(name = "PartnerNo", required = true)
    protected String partnerNo;
    @XmlElement(name = "CustomerNo", required = true)
    protected String customerNo;
    @XmlElement(name = "CustomerType")
    protected short customerType;
    @XmlElement(name = "Password")
    protected String password;
    @XmlElement(name = "SalutationId", nillable = true)
    protected String salutationId;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "Street")
    protected String street;
    @XmlElement(name = "ZipCode")
    protected String zipCode;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "CountryId")
    protected Long countryId;
    @XmlElement(name = "PhoneCountry")
    protected String phoneCountry;
    @XmlElement(name = "PhoneArea")
    protected String phoneArea;
    @XmlElement(name = "PhoneExt")
    protected String phoneExt;
    @XmlElement(name = "FaxCountry")
    protected String faxCountry;
    @XmlElement(name = "FaxArea")
    protected String faxArea;
    @XmlElement(name = "FaxExt")
    protected String faxExt;
    @XmlElement(name = "EMail")
    protected String eMail;
    @XmlElement(name = "CreditCard")
    protected CreditCard creditCard;
    @XmlElement(name = "BonusCard")
    protected BonusCard bonusCard;
    @XmlElement(name = "DateOfBirth")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(name = "DocChannel")
    protected String docChannel;

    /**
     * Gets the value of the logIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogIn() {
        return logIn;
    }

    /**
     * Sets the value of the logIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogIn(String value) {
        this.logIn = value;
    }

    /**
     * Gets the value of the partnerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerNo() {
        return partnerNo;
    }

    /**
     * Sets the value of the partnerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerNo(String value) {
        this.partnerNo = value;
    }

    /**
     * Gets the value of the customerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * Sets the value of the customerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNo(String value) {
        this.customerNo = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     */
    public short getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     */
    public void setCustomerType(short value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the salutationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutationId() {
        return salutationId;
    }

    /**
     * Sets the value of the salutationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutationId(String value) {
        this.salutationId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the countryId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * Sets the value of the countryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCountryId(Long value) {
        this.countryId = value;
    }

    /**
     * Gets the value of the phoneCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneCountry() {
        return phoneCountry;
    }

    /**
     * Sets the value of the phoneCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneCountry(String value) {
        this.phoneCountry = value;
    }

    /**
     * Gets the value of the phoneArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneArea() {
        return phoneArea;
    }

    /**
     * Sets the value of the phoneArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneArea(String value) {
        this.phoneArea = value;
    }

    /**
     * Gets the value of the phoneExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneExt() {
        return phoneExt;
    }

    /**
     * Sets the value of the phoneExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneExt(String value) {
        this.phoneExt = value;
    }

    /**
     * Gets the value of the faxCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxCountry() {
        return faxCountry;
    }

    /**
     * Sets the value of the faxCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxCountry(String value) {
        this.faxCountry = value;
    }

    /**
     * Gets the value of the faxArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxArea() {
        return faxArea;
    }

    /**
     * Sets the value of the faxArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxArea(String value) {
        this.faxArea = value;
    }

    /**
     * Gets the value of the faxExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxExt() {
        return faxExt;
    }

    /**
     * Sets the value of the faxExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxExt(String value) {
        this.faxExt = value;
    }

    /**
     * Gets the value of the eMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

    /**
     * Gets the value of the creditCard property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCard }
     *     
     */
    public CreditCard getCreditCard() {
        return creditCard;
    }

    /**
     * Sets the value of the creditCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCard }
     *     
     */
    public void setCreditCard(CreditCard value) {
        this.creditCard = value;
    }

    /**
     * Gets the value of the bonusCard property.
     * 
     * @return
     *     possible object is
     *     {@link BonusCard }
     *     
     */
    public BonusCard getBonusCard() {
        return bonusCard;
    }

    /**
     * Sets the value of the bonusCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link BonusCard }
     *     
     */
    public void setBonusCard(BonusCard value) {
        this.bonusCard = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the docChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocChannel() {
        return docChannel;
    }

    /**
     * Sets the value of the docChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocChannel(String value) {
        this.docChannel = value;
    }

}
