//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 06:32:33 PM CET 
//


package com.bpcs.suny.tool.xml.request.getcars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Stations" minOccurs="0"/>
 *         &lt;element ref="{}CarCategories" minOccurs="0"/>
 *         &lt;element ref="{}CarForms" minOccurs="0"/>
 *         &lt;element ref="{}Operators" minOccurs="0"/>
 *         &lt;element ref="{}ServiceCatalogs" minOccurs="0"/>
 *         &lt;element ref="{}Suppliers" minOccurs="0"/>
 *         &lt;element ref="{common}StationLocationTypes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stations",
    "carCategories",
    "carForms",
    "operators",
    "serviceCatalogs",
    "suppliers",
    "stationLocationTypes"
})
@XmlRootElement(name = "Filter")
public class Filter {

    @XmlElement(name = "Stations")
    protected Stations stations;
    @XmlElement(name = "CarCategories")
    protected CarCategories carCategories;
    @XmlElement(name = "CarForms")
    protected CarForms carForms;
    @XmlElement(name = "Operators")
    protected Operators operators;
    @XmlElement(name = "ServiceCatalogs")
    protected ServiceCatalogs serviceCatalogs;
    @XmlElement(name = "Suppliers")
    protected Suppliers suppliers;
    @XmlElement(name = "StationLocationTypes", namespace = "common")
    protected String stationLocationTypes;

    /**
     * Contains Station objects. Ignored if PickUpStationId is set
     * 
     * @return
     *     possible object is
     *     {@link Stations }
     *     
     */
    public Stations getStations() {
        return stations;
    }

    /**
     * Sets the value of the stations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stations }
     *     
     */
    public void setStations(Stations value) {
        this.stations = value;
    }

    /**
     * Gets the value of the carCategories property.
     * 
     * @return
     *     possible object is
     *     {@link CarCategories }
     *     
     */
    public CarCategories getCarCategories() {
        return carCategories;
    }

    /**
     * Sets the value of the carCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarCategories }
     *     
     */
    public void setCarCategories(CarCategories value) {
        this.carCategories = value;
    }

    /**
     * Gets the value of the carForms property.
     * 
     * @return
     *     possible object is
     *     {@link CarForms }
     *     
     */
    public CarForms getCarForms() {
        return carForms;
    }

    /**
     * Sets the value of the carForms property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarForms }
     *     
     */
    public void setCarForms(CarForms value) {
        this.carForms = value;
    }

    /**
     * Gets the value of the operators property.
     * 
     * @return
     *     possible object is
     *     {@link Operators }
     *     
     */
    public Operators getOperators() {
        return operators;
    }

    /**
     * Sets the value of the operators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operators }
     *     
     */
    public void setOperators(Operators value) {
        this.operators = value;
    }

    /**
     * Gets the value of the serviceCatalogs property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCatalogs }
     *     
     */
    public ServiceCatalogs getServiceCatalogs() {
        return serviceCatalogs;
    }

    /**
     * Sets the value of the serviceCatalogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCatalogs }
     *     
     */
    public void setServiceCatalogs(ServiceCatalogs value) {
        this.serviceCatalogs = value;
    }

    /**
     * Contains Supplier objects. Ignored if PickUpSupplierId is set
     * 
     * @return
     *     possible object is
     *     {@link Suppliers }
     *     
     */
    public Suppliers getSuppliers() {
        return suppliers;
    }

    /**
     * Sets the value of the suppliers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Suppliers }
     *     
     */
    public void setSuppliers(Suppliers value) {
        this.suppliers = value;
    }

    /**
     * Gets the value of the stationLocationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationLocationTypes() {
        return stationLocationTypes;
    }

    /**
     * Sets the value of the stationLocationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationLocationTypes(String value) {
        this.stationLocationTypes = value;
    }

}
